### ISSUE TITLE
How to configure fluent-bit sub-chart updateStrategy?

### ISSUE THREAD

**Issue by sepulworld** [SumoLogic/sumologic-kubernetes-collection#1652]
I can't seem to find where we can configure the fluent-bit sub-chart updateStrategy. Could someone point me in the right direction? Or is this a missing feature?

**Comment by sepulworld** [comment]
It seems to be missing. 

https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1653

**Comment by sepulworld** [comment]
we have a 100+ cluster that takes way too long to update with the current default updateStrategy that fluent-bit helm chart uses.

**Comment by frankreno** [comment]
You can do this w/o a PR.  Any property in the fluent-bit helm chart can be set during out chart's installation since it is just a sub-chart. You just need to pass in the appropriate key.  So the example you added in the PR should be able to be set using `--set fluent-bit.updateStrategy.type=RollingUpdate --set fluent-bit.updateStrategy.rollingUpdate.maxUnavailable=1`

We do not document all properties of the sub-charts as there would be so many of them, but any property in the sub-chart can be set via `--set` or in a values.yaml using the `fluent-bit` prefix.

https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/deploy/helm/sumologic#configuration

**Comment by sepulworld** [comment]
Ah! Thank you Frank!
