### ISSUE TITLE
CoreDNS Metric Name changes in 1.7

### ISSUE THREAD

**Issue by frankreno** [SumoLogic/sumologic-kubernetes-collection#1700]
https://coredns.io/2020/06/15/coredns-1.7.0-release/#metric-changes

coredns_dns_request_count_total -> coredns_dns_requests_total
coredns_dns_response_rcode_count_total -> coredns_dns_responses_total
coredns_forward_request_count_total -> coredns_forward_requests_total
coredns_cache_size -> coredns_cache_entries

We will need to adjust the remote write conf to support sending old and new and coordinate a new app release.

**Comment by pmalek-sumo** [comment]
It seems @sumo-drosiek made it trip back in time and fixed this already in December 2020, https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1200

I don't see any action required for this from collection chart perspective, there might be something required to be done from app's perspective but I'm leaning towards closing the issue here.
