### ISSUE TITLE
Change configuration of Fluent Bit and Prometheus to allow sending data to OtelCol

### ISSUE THREAD

**Issue by astencel-sumo** [SumoLogic/sumologic-kubernetes-collection#1757]
In #1741, we have introduced a workaround for Fluent Bit and Prometheus to be able to send data to OtelCol by naming OtelCol's service the same as Fluentd's service.

This should be fixed with a breaking change in v3.0 where we change the configuration of Fluent Bit and Prometheus so that OtelCol can keep its own service name and Fluent Bit and Prometheus is restarted upon metadata provider change.

**Comment by frankreno** [comment]
We should revisit if this is needed because the fluent-bit and Prometheus config use environment variables so we should be able to dynamically create the correct service based on the chosen metadata enrichment -https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/chart-configmap.yaml#L6-L8

**Comment by pmalek-sumo** [comment]
Thanks writing about this @frankreno.

The tricky part - that will introduce the breaking change - is the change in fluent-bit output's config: https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/a23b76fb6b8719d4896f0c66faea364dad37980c/deploy/helm/sumologic/values.yaml#L1038-L1049

Ideally - as long as we keep using fluent-bit - we'd separate node and containers logs so that they go to separate endpoints/services. Then it will be easier to process them as they each have a bit different processing logic built around them.

**Comment by perk-sumo** [comment]
We should be able to use service names that match both OTC and Fluentd at the same time, eg.
`logs.metadata...` and `metrics.metadata...`

**Comment by rnishtala-sumo** [comment]
These two PRs have been raised/merged for this issue:
- https://github.com/SumoLogic/sumologic-kubernetes-collection/commit/396843a264c0d5b516fb118e8ad0ec47943575da
- https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2621
