### ISSUE TITLE
how to remove ADD_TIMESTAMP and ADD_STREAM from the application level

### ISSUE THREAD

**Issue by renperez** [SumoLogic/sumologic-kubernetes-collection#526]
I'm running fluentd and fluentbit inside our cluster with this env enabled. I want to know if there is a way to disable this using an annotation from the application k8s deployment manifest. so far the only annotations i have are these:
annotations:
        sumologic.com/sourceCategory: test-stage-application
        sumologic.com/kubernetes_meta_reduce: "true"
        sumologic.com/format: text

- name: ADD_TIMESTAMP
          value: "true"
        - name: ADD_STREAM
          value: "true"

**Comment by vsinghal13** [comment]
Hi, I think we can still use those as annotations. They are exposed as ENV.envshttps://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v0.17.0/deploy/helm/sumologic/templates/deployment.yaml#L180

@samjsong could you please confirm if the annotations for these will work>

**Comment by renperez** [comment]
thanks @vsinghal13. would the annotations be something like this? sumologic.com/add_timestamp: false
sumologic.com/add_stream: false

**Comment by renperez** [comment]
ah it looks like something like this: sumologic.addTimestamp
sumologic.addStream

**Comment by renperez** [comment]
@vsinghal13 this worked for me. many thanks

**Comment by vsinghal13** [comment]
@renperez could you please confirm how use used the annotations?

**Comment by 4ragumurthy** [comment]
@renperez Cc  As discussed today, this is not working and it is not designed to work. It looked it was working for you because of the following annotation
sumologic.com/format: text

When the format changed to fields, in that case, the setting in the values.yaml takes effect
---------------------------------
https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v0.17.0/deploy/helm/sumologic/values.yaml#L152

  ## Option to control adding stream to logs.
  addStream: "true"

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/v0.17.0/deploy/helm/sumologic/values.yaml#L155
  ## Option to control adding time to logs.
  addTime: "true"
------------------------
@vsinghal13 can you re-open this issue?

**Comment by renperez** [comment]
Thanks guys, please keep me posted if this feature becomes available. I am
also in the process of discussing with our developers to standardize our
logging output to use json or text but not both.

Ren Perez
Tunein | Devops
Email: rperez@tunein.com
Mobile: 925-698-4637

**Comment by frankreno** [comment]
At the moment, we do not plan to add annotation support for these.  It is possible to modify the fluentD configuration to control this behavior.
