### ISSUE TITLE
How to provide authentication credentials with the helm deployment?

### ISSUE THREAD

**Issue by duncaan** [SumoLogic/sumologic-kubernetes-collection#938]
With Docker's recent pricing changes https://www.docker.com/pricing, what's the suggestion on how to set up an account to either authenticate with dockerhub or another private repo acting as a mirror?

**Comment by pmalek-sumo** [comment]
Hi @duncaan,

Do you mind describing your use case?

The newest docker changes (from November 1) indicate that there's a limit of 100 pulls per 6 hours per IP for unauthenticated users. Does your use case involve exhausting this limit because of pulls of other images on nodes that also run Sumo Logic collection?

**Comment by duncaan** [comment]
Yes - that would be my concern.  I guess we could always mirror the images locally in our own repo.
I guess my suggestion would be to host them in multiple places, like github's docker registry which has no pull limit.

**Comment by davidmrhea** [comment]
I agree with the need for this.  Could you please add the ability to configure `imagePullSecrets` to the Helm charts?  https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret
That is a common option in other Helm charts.

**Comment by pmalek-sumo** [comment]
@duncaan @davidmrhea There's a PR that tries to address that: https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/1104

Feel free to comment.
